#!/bin/python3

from grading import graders

problem_id = 'sum'
test_cases = [('1.in', '1.out'), ('2.in', '2.out'), ('3.in', '3.out'), ('4.in', '4.out')]
options = {'compute_diff': True, 'diff_max_lines': 100, 'output_diff_for': [], 'treat_non_zero_as_runtime_error': True, 'diff_context_lines': 3}
weights = [1.0, 1.0, 1.0, 1.0]

graders.handle_problem_action(problem_id, test_cases, options=options, weights=weights)
