#!/bin/python3

from grading import graders

problem_id = 'triangle'
test_cases = [('1.in', '1.out'), ('10.in', '10.out'), ('2.in', '2.out'), ('3.in', '3.out'), ('4.in', '4.out'), ('5.in', '5.out'), ('6.in', '6.out'), ('7.in', '7.out'), ('8.in', '8.out'), ('9.in', '9.out')]
options = {'compute_diff': True, 'treat_non_zero_as_runtime_error': True, 'diff_max_lines': 100, 'output_diff_for': [], 'diff_context_lines': 3}
weights = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

graders.handle_problem_action(problem_id, test_cases, options=options, weights=weights)
